### ISSUE TITLE
Add an open source license

### ISSUE THREAD

**Issue by kbloom** [MajicDesigns/LCD-BigNum#1]
I'd like to incorporate this font into my small open source project with minor modifications (namely, changing LiquidCrystal to SerLCD) but can't do so without a proper open source license. Would you be willing to add appropriate copyright information to license this under the Apache 2 license?

**Comment by MajicDesigns** [comment]
Thanks for reaching out.

Feel free to do what you want with this code. It is example code that everyone can use in their own projects however they wish. Proper attribution would be appreciated but not expected.
